### ISSUE TITLE
super user pass

### ISSUE THREAD

**Issue by Andrea** [zyga/vagrant-desktop-images#11]
Hi there

I have the vm running :) thanks for that
I was wondering is there any special super user password I should know? I went to the Ubuntu software center and when asked to authenticate it fails when I use _vagrant_ (I was able to log after I updated the machine to a newer version of the distro)

![capture](https://cloud.githubusercontent.com/assets/3103/6249400/df7fbf10-b77e-11e4-9a8b-549db6cb4134.JPG)

(Note: I haven't used linux in a while so this could just be me not know how to do something, sorry if that is the case :) )

**Comment by zyga** [comment]
Hey

The password for the ubuntu user was IIRC empty (no password).

Best regards
ZK

2015-02-18 16:01 GMT+01:00 Andrea <notifications@github.com>:

**Comment by Andrea** [comment]
Hi there

Tried that and some other options but no luck. I ended up starting a different vm and it all just worked :D
Thanks :)
